@startuml

[<<Web Server>>\nNginx Front End] as Nginx
[<<External>> Image Hosting] as IH
package "Deep Learning Application" {
    [<<Application Server>>\nDjango] as Django
    [<<Message Broker>>\n RabbitMQ] as MB
}

interface "HTTP 8080" as HTTP
interface "WGSI 8086" as DjServer
Nginx -left-> HTTP
Nginx -right-> DjServer
DjServer -down-> Django
Django -right- MB
Django -down- IH

@enduml
