@startuml

[<<Web Server>>\nNginx Front End] as Nginx

package "Deep Learning Application" {
    [<<Application Server>>\nDjango] as Django
    database "Redis" {
        [<<Message Broker>>] as MB
    }
}
database "SQLite" {
 [<<Database>>] as DB
}
interface "HTTP 8080" as HTTP
interface "WGSI 8086" as DjServer
interface "3306" as DBPort
Nginx -left-> HTTP
Nginx -right-> DjServer
DjServer -down-> Django
Django -down-> DBPort
Django -right- MB
DBPort -right-> DB

@enduml
