@startuml
actor User #red
participant Nginx
participant Kiera
participant Cache
scale 1920*1080
'API Spec'

User->Nginx: GET /rec/status (Training Status)
activate Nginx
Nginx->Kiera: GET /rec/status (Training Status)
activate Kiera
Kiera->Nginx: 200 OK\n{'status': 'READY'}
deactivate Kiera
Nginx->User: 200 OK\n{'status': 'READY'}
deactivate Nginx

User->Nginx: POST /rec/train (Init Training)
activate Nginx
Nginx->Kiera: POST /rec/train (Init Training)
activate Kiera
Kiera->Nginx: 202 Accepted
Nginx->User: 202 Accepted
deactivate Nginx
Kiera->Kiera: <<Async>>\nLoad Data Set
Kiera->Kiera: <<Async>>\nPreprocess Data\nCreate Model\nInitiate Deep Learning

User->Nginx: GET /rec/status (Training Status)
activate Nginx
Nginx->Kiera: GET /rec/status (Training Status)
alt Deep Learning Complete
  Kiera->Nginx: 200 OK\n{'state': 'COMPLETED'}
  Nginx->User: 200 OK\n{'state': 'COMPLETED'}
else Deep Learning in Progress
  Kiera->Nginx: 202 Accepted\n{'state': 'IN_PROGRESS'}
  Nginx->User: 202 Accepted\n{'state': 'IN_PROGRESS'}
end
deactivate Nginx

User->Nginx: GET /rec/accuracy (Testing Accuracy)
activate Nginx
Nginx->Kiera: /rec/accuracy (Testing Accuracy)
alt Deep Learning Complete
  Kiera->Nginx: 200 OK\n{accuracy: ''}
  Nginx->User: 200 OK\n{accuracy: ''}
else Deep Learning in Progress
  Kiera->Nginx: 202 Accepted
  Nginx->User: 202 Accepted
else Deep Learning not Initiated
  Kiera->Nginx: 412 Precondition Failed
  Nginx->User: 412 Precondition Failed
end
deactivate Nginx

User->Nginx: GET Prediction\nIndex
activate Nginx
Nginx->Kiera: GET Prediction\nIndex
alt Deep Learning Complete
  Kiera->Cache: Check if Prediction exists for requested index
  activate Cache
  alt Prediction Exists
    Cache->Kiera: {Predicted Label, Actual Label}
  else
    Kiera->Kiera: Use Input Index as Test Data\nRun Test Data through trained NN Model
  end
  deactivate Cache
  Kiera->Nginx: 200 OK {Predicted Label, Actual Label}
  Nginx->User: 200 OK {Predicted Label, Actual Label}
else Deep Learning in Progress
  Kiera->Nginx: 202 Accepted
  Nginx->User: 202 Accepted
else Index Out of Range
  Kiera->Nginx: 400 Bad Request
  Nginx->User: 400 Bad Request
end
deactivate Nginx
destroy Nginx
destroy Kiera
@enduml
